kind: Job
apiVersion: batch/v1
metadata:
  name: helicoptericing
spec:
  template:
    spec:
      containers:
      - name: helicoptericing
        # image: "test-get-masked-image"
        # image: python:3.11-slim
        # image: pytorch/pytorch
        image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
        workingDir: /storage
        # command: ["ls"]
        command: ["sh", "instructions.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
      # imagePullPolicy: Never
  backoffLimit: 0